// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcuSweGT88ba7dGF3XlFzF8YFZ5VNoy6A',
    appId: '1:791720757772:web:88b1820dd0f536bfd63c29',
    messagingSenderId: '791720757772',
    projectId: 'nconnect-f321f',
    authDomain: 'nconnect-f321f.firebaseapp.com',
    storageBucket: 'nconnect-f321f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf02UWFHIMzqRLknxRqdzmGx2Wvt9NKfE',
    appId: '1:791720757772:android:0043a74281a5b080d63c29',
    messagingSenderId: '791720757772',
    projectId: 'nconnect-f321f',
    storageBucket: 'nconnect-f321f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHRnmKkf0DhVMfcDmDspXCbZl1akbpQQw',
    appId: '1:791720757772:ios:58b1a460c3cb49d9d63c29',
    messagingSenderId: '791720757772',
    projectId: 'nconnect-f321f',
    storageBucket: 'nconnect-f321f.appspot.com',
    iosBundleId: 'com.example.nconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHRnmKkf0DhVMfcDmDspXCbZl1akbpQQw',
    appId: '1:791720757772:ios:0b0013545ad96b8bd63c29',
    messagingSenderId: '791720757772',
    projectId: 'nconnect-f321f',
    storageBucket: 'nconnect-f321f.appspot.com',
    iosBundleId: 'com.example.nconnect.RunnerTests',
  );
}
